# Generated by Django 6.1.1 on 2026-10-07 16:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank for unlimited', null=True)),
                ('last_generated', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('reminder_days', models.IntegerField(default=3, help_text='Days before due date to send reminder')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_transactions', to='transactions.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recurring Transaction',
                'verbose_name_plural': 'Recurring Transactions',
                'ordering': ['next_due_date'],
            },
        ),
        migrations.CreateModel(
            name='RecurringTransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('generated_transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_log', to='transactions.transaction')),
                ('recurring_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='recurring.recurringtransaction')),
            ],
            options={
                'verbose_name': 'Recurring Transaction Log',
                'verbose_name_plural': 'Recurring Transaction Logs',
                'ordering': ['-generated_date'],
            },
        ),
    ]
